### ISSUE TITLE
Generated gRPC code doesn't compile with Java 12

### ISSUE THREAD

**Issue by Egorand** [square/wire#1003]
Looks like `javax.annotation.Generated` has been removed from the JDK.

**Comment by JakeWharton** [comment]
It caused a package split. You have to use .processing.Generated for 9+

**Comment by oldergod** [comment]
Does it have to be included in 3.0?

The bug is part of the Google generated code, not wire's, and it only concerns `wire-grpc-tests` for we use it only for the implementation of our mocked gRPC server.

I'll check if there is a way to tweak that via the protobuf plugin otherwise, I'd say it's a google bug.
