### ISSUE TITLE
Could you publish gradle plugin to gradle plugin portal?

### ISSUE THREAD

**Issue by anatawa12** [square/wire#1944]
The plugin `'com.squareup.wire'` looks not published to gradle plugin portal so I can't use wire plugin with this syntax said in [documentation](https://github.com/square/wire/blob/master/wire-library/docs/wire_compiler.md)

```gradle
plugins {
  id 'com.squareup.wire'
  // even with
  // id 'com.squareup.wire' version "3.7.0"
}
```

Current workaround: add this code to settings.gradle.kts

```kotlin
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.squareup.wire") {
                useModule("com.squareup.wire:wire-gradle-plugin:${requested.version}")
            }
        }
    }
}
```

**Comment by JakeWharton** [comment]
Generally, no, we haven't ever pursued Gradle's proprietary portal. Especially since they introduced the ability to resolve plugins from any artifact repository (ironically with more verbosity than the `classpath` syntax).

I'll copy what I wrote on the request for this from SQLDelight:

> I'm not a huge fan of this mechanism so it's a very low priority for me. If it can be transparently integrated into the release process as an _secondary_ publishing location then that's fine, but releasing the Gradle plugin as a jar to Maven central should be the primary distribution mechanism.

Wire still doesn't have one-click deploys like SQLDelight, so getting that seems like a blocker to anything here. And that's assuming you can fully automate releasing to their proprietary place.

**Comment by oldergod** [comment]
I thought @jrodbx started publishing the plugin with https://github.com/square/wire/pull/1852
Is it something different? Or is it not working?

**Comment by JakeWharton** [comment]
The plugin marker allows it to be resolved, but I believe you still have to tell it to look in mavenCentral rather than their proprietary artifact host.

**Comment by anatawa12** [comment]
Umm... it looks no plugin marker archifact on [maven central] and I can't apply `com.squareup.wire` with plugins block even with `pluginManagement { repositories { mavenCentral() } }` in settings.gradle(.kts).

[maven central]: https://repo1.maven.org/maven2/com/squareup/wire/

**Comment by oldergod** [comment]
Fixed with the most recent Wire 4 alpha.
