### ISSUE TITLE
Expose type adapter in public API

### ISSUE THREAD

**Issue by JakeWharton** [square/wire#209]
For libraries like Retrofit, it is beneficial to be able to do a one-time look-up of an adapter which is a reader of types from data as well a writer of types to data. Libraries like Gson, Moshi, Jackson, and even Google protobuf have similar concepts.

We should expose this as a first-party mechanism and API.

Not a strict proposal but merely an indicator as to what I'm looking for:
```java
<T extends Message> MessageAdapter<T> adapter(Class<T> cls);
```
```java
interface MessageAdapter<T extends Message> {
  T read(Source source);
  void write(T value, Sink sink);
}
```

**Comment by vanvlack** [comment]
Unsure if this is what you're getting at, but it would be nice to be able to generate mutiple types of beans from a proto. For example, I would like to generate Wire compatible protobuf beans and Jackson annotated JSON beans. The latter, of which, I could write an extension for that Wire would be able to use and pump out the bean with.

Ideally, I could write out one class that is handled by both (since Wire beans are very light weight and include zero serialization code in them).

**Comment by JakeWharton** [comment]
The v2 compiler will have the notion of a plugin which hands you model objects and lets you do whatever you want with them. The generating of Wire-runtime-compatible classes will be one of these plugins. We have a lot of other needs for plugins internally (generating Retrofit service interfaces, generating assertion classes, generating Kotlin extension functions, etc.).

This issue, though, is way to hold a generic-friendly reference to an object for converting to and from a proto in the Wire runtime.

**Comment by vanvlack** [comment]
@JakeWharton sounds like a plan, thanks for the response.
