### ISSUE TITLE
AndroidMessage do not generate a serialVersionUID 

### ISSUE THREAD

**Issue by maxjyhu** [square/wire#2247]
AndroidMessage do not generate a serialVersionUID

**Comment by oldergod** [comment]
Why is it a problem?

**Comment by maxjyhu** [comment]
> Why is it a problem?

In Java, if a class implements the Serializable interface, objects of that class can be serialized and deserialized. During the process of serialization and deserialization, the Java virtual machine needs to determine whether the versions of each class are consistent to ensure the correctness of the deserialization operation. serialVersionUID is used to identify the unique identifier of the version of a class. If serialVersionUID is not specified, the Java virtual machine will automatically generate a serialVersionUID based on the structure of the class, but this will cause the automatically generated serialVersionUID to change when the structure of the class changes, resulting in deserialization failure. Therefore, to ensure consistency of class versions, it is necessary to manually specify serialVersionUID.

**Comment by oldergod** [comment]
Ok, so we generate them for them when generating types. So a type generated in java or kotlin will have it.
It is actually useless to define them in their parent abstract class. I'll close the ticket because we're in a good state already.

https://github.com/square/wire/blob/master/wire-java-generator/src/main/java/com/squareup/wire/java/JavaGenerator.java#L697
https://github.com/square/wire/blob/master/wire-kotlin-generator/src/main/java/com/squareup/wire/kotlin/KotlinGenerator.kt#L595
