### ISSUE TITLE
ReflectiveMessageAdapter.ImmutableList is Serializable, Missing In Action

### ISSUE THREAD

**Issue by swankjesse** [square/wire#319]
We moved this class recently. That's going to break Java serialization compatibility with the next release. We should make sure we're comfortable with this.

**Comment by swankjesse** [comment]
@danrice-square @JakeWharton opinions?

**Comment by JakeWharton** [comment]
It doesn't get included in the serialized form of a message so the only way
would have been if you took a list and serialized it elsewhere.

Since we're already breaking all the things in v2, I'd prefer to not care
about old client but future proof by having it replace itself with a Java
collection when serialized. This way we're never on the hook for
compatibility.

**Comment by swankjesse** [comment]
Perfect.
